name: 'Recovery Builder'
on:
  workflow_dispatch:
    inputs:
      manifest:git://github.com/PitchBlackRecoveryProject/manifest_pb.git -b android-11.0
        description: 'Recovery Manifest URL with -b branch'
        required: true
      vendor:lenovo
        description: 'Device Company / OEM / Vendor, i.e., xiaomi'
        required: true
      codename:doom
        description: 'Device Codename i.e rosy'
        required: true
      dt_link:https://github.com/jbhacktheplanet/lenovo_doom
        description: 'Device Tree link, with optional -b branch'
        required: true
      kernel_link:
        description: 'Kernel repo link with optional -b branch, Use if not prebuilt'
        required: false
      req_qcom_commonsys:true
        description: 'If require QCOM commonsys, set this to true, i.e., SHRP needs this'
        required: true
        default: 'false'
      cryptfs_fix:true
        description: 'If require to fix cryptfs_hw conflict, set this to true'
        required: true
        default: 'false'
      target:bootimage
        description: 'Build Target, i.e., recoveryimage'
        required: true
        default: 'recoveryimage'
      flavor:eng
        description: 'Build flavor, i.e., userdebug or eng'
        required: true
        default: 'eng'
      extra_cmd:
        description: 'Do extra commands followed by && after each cmds, i.e rm -rf repo && git clone repo'
        required: false

env:
  MANIFEST: ${{ github.event.inputs.manifest }}
  DT_LINK: ${{ github.event.inputs.dt_link }}
  VENDOR: ${{ github.event.inputs.vendor }}
  CODENAME: ${{ github.event.inputs.codename }}
  KERNEL_LINK: ${{ github.event.inputs.kernel_link }}
  TARGET: ${{ github.event.inputs.target }}
  FLAVOR: ${{ github.event.inputs.flavor }}
  EXTRA_CMD: ${{ github.event.inputs.extra_cmd }}
  REQ_QCOM_COMMONSYS: ${{ github.event.inputs.req_qcom_commonsys }}
  CRYPTFS_FIX : ${{ github.event.inputs.cryptfs_fix }}
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Cleanup Space
        uses: rokibhasansagar/slimhub_actions@main

      - name: Initializing Build Environment
        run: bash prepare.sh

      - name: Make ${{ env.TARGET }} for ${{ env.CODENAME }}
        run: bash builder.sh

      - name: Release Builds
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "latest"
         prerelease: false
         title: "Recovery Automation By Area69Lab"
         files: |
            /home/runner/work/out/target/product/*/*.zip
            /home/runner/work/out/target/product/*/*.img
